### ISSUE TITLE
Configure Animal Node model

### ISSUE THREAD

**Issue by AHalic** [UFES20221BDCOMP/T1-Beatriz-Sophie#10]
- [x] Query to add animal -> post
- [x] #123
- [x] Query to edit pet's information
- [x] Query to get all pet's informations
- [x] Query to get information from a specific pet by id
- [x] Query to get schedule from today
- [x] Query to get schedule history

**Comment by beamaia** [comment]
- [ ] Get all animals
- [ ] Get animal's by id
- [ ] Get animal's schedule from today
- [ ] Get animal's schedule history
- [ ] Post
- [ ] Patch
- [ ] Delete cascade
