### ISSUE TITLE
Define Schema

### ISSUE THREAD

**Issue by AHalic** [UFES20221BDCOMP/T1-Beatriz-Sophie#3]
- [x] Create model
- [x] Define Person table
- [x] Define Animal table
- [x] Define AnimalType table
- [x] Define Service table
- [x] Define Schedule table
- [x] Create seed
- [x] Determine PERSON_SIZE , ANIMAL_SIZE and SCHEDULE_SIZE

**Comment by beamaia** [comment]
@rlaiola questões sobre o modelo

A gente fez um modelo inicial para o problema ([esta imagem](https://raw.githubusercontent.com/UFES20221BDCOMP/T1-Beatriz-Sophie/dev1.0/docs/modelo.png?token=GHSAT0AAAAAABUZ272USCNDJQC5SZVLOOZKYUYVIHA)). Na nossa modelagem a gente pensou no uso de 3 tabelas:
- Tabela de pessoas
- Tabela de animais
- Tabelas de tipos de animais

Mas o [desafio](https://github.com/petlove/vagas/tree/master/backend-ruby) utilizava apenas duas:
- Tabela de pessoas
- Tabela de animais

A gente pensou que o uso duma terceira tabela com o tipo de animais seria ideal para não ter a possibilidade de inserção de tipos de animais com typos ou grafias diferentes (ex. cachorro, CACHORRO, cachoro). Além disso, o exemplo do desafio parenta utilizar o nome como chave primária das pessoas. A gente pensou que seria melhor utilizar o documento, sendo esse documento o CPF e específico ao domínio do Brasil.

Outras decisão feita:
- Um animal só pode ter um dono

Depois tinhamos uma dúvida sobre nosso API. Dado uma situação em que um animal for cadastrado e seu tipo não existe, seria interessante implementar no API o poder de adicionar/modificar tipos de animais? A gente achou que talvez não seria o ideal se fosse no contexto do caixa cadastrando o pet, mas ficamos com dúvida.

**Comment by rlaiola** [comment]
@beamaia @AHalic 

> 
> A gente fez um modelo inicial para o problema ([esta imagem](https://raw.githubusercontent.com/UFES20221BDCOMP/T1-Beatriz-Sophie/dev1.0/docs/modelo.png?token=GHSAT0AAAAAABUZ272USCNDJQC5SZVLOOZKYUYVIHA)). 

Recebo uma mensagem de erro (404) ao tentar abrir a imagem do modelo.

> Na nossa modelagem a gente pensou no uso de 3 tabelas:
> 
> * Tabela de pessoas
> * Tabela de animais
> * Tabelas de tipos de animais
> 
> Mas o [desafio](https://github.com/petlove/vagas/tree/master/backend-ruby) utilizava apenas duas:
> 
> * Tabela de pessoas
> * Tabela de animais
> 

Sem problemas!

> A gente pensou que o uso duma terceira tabela com o tipo de animais seria ideal para não ter a possibilidade de inserção de tipos de animais com typos ou grafias diferentes (ex. cachorro, CACHORRO, cachoro). Além disso, o exemplo do desafio parenta utilizar o nome como chave primária das pessoas. A gente pensou que seria melhor utilizar o documento, sendo esse documento o CPF e específico ao domínio do Brasil.

OK

> 
> Outras decisão feita:
> 
> * Um animal só pode ter um dono
> 
 É o que indica a tabela de animais.

> Depois tinhamos uma dúvida sobre nosso API. Dado uma situação em que um animal for cadastrado e seu tipo não existe, seria interessante implementar no API o poder de adicionar/modificar tipos de animais? A gente achou que talvez não seria o ideal se fosse no contexto do caixa cadastrando o pet, mas ficamos com dúvida.

O que vocês querem dizer com o "tipo não existe"? Ele é desconhecido ou inexistente (null)? Uma coisa é a implementação da API, outra é como essa será disponibilizada para os usuários (por ex., o atendente) através de uma UI. Parece prudente permitir a inserção dos tipos, de acordo com a decisão que vocês tomaram acima.

**Comment by beamaia** [comment]
> O que vocês querem dizer com o "tipo não existe"? 

A gente estava pensando mais no contexto em que esta API seria utilizada, se a pessoa que fosse cadastrar um animal e encontrasse que esse tipo de animal não pertence a tabela de animais (tipo um tigre ou um animal selvagem que nunca foi incluído), no caso de inexistente (null) mesmo. Mas a resposta já respondeu tudo.

O link da imagem (caso queira ver): https://github.com/UFES20221BDCOMP/T1-Beatriz-Sophie/blob/dev1.0/docs/modelo.png (espero que funcione agora).

Muito obrigada!

**Comment by beamaia** [comment]
Professor @rlaiola , 

A gente pensou em atualizar o modelo para esse: https://github.com/UFES20221BDCOMP/T1-Beatriz-Sophie/blob/configure-schema/docs/modelo.png

Olhando o desafio, a gente pensou que algumas coisas não fariam sentido em um contexto de uma clínica veterinária e nos baseamos no desafio https://github.com/petlove/vagas/tree/master/backend-java .

**Comment by beamaia** [comment]
close #21
