### ISSUE TITLE
Modify db script

### ISSUE THREAD

**Issue by AHalic** [UFES20221BDCOMP/T1-Beatriz-Sophie#49]
- [x] add id person to schedule table
- [x] add services constraint (price > 0)
- [x] add to foreign keys  ON DELETE CASCADE
- [x] add constraint UNIQUE to date_service

**Comment by AHalic** [comment]
dúvidas: 
- o timestamp do date_service ta armazenando o horario msm?

**Comment by beamaia** [comment]
@AHalic sim, os horarios sao em 15-15 min
