### ISSUE TITLE
Configure Person Node model

### ISSUE THREAD

**Issue by beamaia** [UFES20221BDCOMP/T1-Beatriz-Sophie#9]
- [x] #34
- [x] #35
       Constraints:
          Has to be 18 or older to own a pet
- [x] #36
    Constraint:
       Must delete animals beforehand. 
       Must delete schedule beforehand
- [x] #37
- [x] #38
- [x] #39
- [x] #42

**Comment by AHalic** [comment]
- [ ] Get everyone
- [ ] Get by id (also returns pet's id and name)
- [ ] Get all of the person's pet's schedules from today
- [ ] Get all of the person's pet's schedules history
- [ ] Post
- [ ] Patch
- [ ] Delete cascade
